randconnexe: randconnexe.o
	gcc $(CFLAGS) randconnexe.o -o randconnexe -L $(TAG)/lib/ -lgraphe
	#rm randconnexe.o

randconnexe.o: randconnexe.c 
	gcc $(CFLAGS) -c randconnexe.c -I $(TAG)/lib/headers/

