CFLAGS=-Wall -g

all: EstPalindrome TriSelection Syracuse


EstPalindrome: EstPalindrome.c
	gcc $(CFLAGS) -o EstPalindrome EstPalindrome.c

TriSelection: TriSelection.c
	gcc $(CFLAGS) -o TriSelection TriSelection.c

Syracuse: Syracuse.c
	gcc $(CFLAGS) -o Syracuse Syracuse.c


